name: merging_prototype
channels:
  - conda-forge
dependencies:
  - pycomlink
  # depenendencies of poligrain (maybe mostly covered by pycomlink)
  - netcdf4
  - xarray
  - matplotlib
  - pyproj
  - scipy
  - sparse
  - shapely
